Repository Tabeyouka/project_TABEYOUKA_laravel-deployment-repo, pull requests merged in 2023-06, with the labels that each got.

#19 ✨ feat : Update schema for database migration
  database/migrations/2023_06_26_151259_create_users_table.php
  database/migrations/2023_06_26_151317_create_restaurants_table.php
  database/migrations/2023_06_26_151322_create_reviews_table.php
  database/migrations/2023_06_26_151328_create_follows_table.php
Labels: ✨ Feature

#23 ✨ feat : Implement restaurant search based on location and food genre & user's location
  app/Search/Actions/FindNearbyRestaurantsAction.php
  app/Search/Actions/SearchRestaurantsAction.php
  app/Search/Domain/Restaurant.php
  app/Search/Responders/NearbyRestaurantsResponder.php
  app/Search/Responders/SearchRestaurantsResponder.php
  app/Services/RecruitApiService.php
  composer.json
  composer.lock
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2014_10_12_100000_create_password_reset_tokens_table.php
  database/migrations/2019_08_19_000000_create_failed_jobs_table.php
  database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
  routes/api.php
Labels: ✨ Feature

#24 ✨ feat : Add migration for user_genre_preferences and likes tables
  database/migrations/2023_06_26_151322_create_reviews_table.php
  database/migrations/2023_06_28_104335_create_user_genre_preferences_table.php
  database/migrations/2023_06_28_104341_create_likes_table.php
  database/migrations/2023_06_28_104347_add_profile_image_to_users_table.php
Labels: ✨ Feature

#25 🎨 refactor : Updated variable names in .env file for improved logic i…
  app/Services/RecruitApiService.php
Labels: 🔨 Refactor

#27 [#7] ✨ feat : Implement personalized restaurant recommendation logic based on user preferences
  app/Recommendation/Actions/RecommendRestaurantsAction.php
  app/Recommendation/Domain/UserGenrePreference.php
  app/Recommendation/Responders/RecommendRestaurantsResponder.php
  app/Search/Actions/FindNearbyRestaurantsAction.php
  app/Search/Actions/SearchRestaurantsAction.php
  app/Search/Domain/Restaurant.php
  app/Search/Responders/FindNearbyRestaurantsResponder.php
  app/Search/Responders/SearchRestaurantsResponder.php
  app/Services/RecruitApiService.php
  database/migrations/2023_06_28_104335_create_user_genre_preferences_table.php
  routes/api.php
Labels: ✨ Feature, 🔨 Refactor

#30 ✨feat: Implemented register restaurant and create review.
  .editorconfig
  app/Models/Like.php
  app/Models/Restaurant.php
  app/Models/Review.php
  app/Models/User.php
  app/Restaurant/Actions/CreateRestaurantAction.php
  app/Restaurant/Domain/CreateRestaurantDomain.php
  app/Restaurant/Responders/CreateRestaurantResponder.php
  app/Review/Actions/CreateReviewAction.php
  app/Review/Actions/GetReviewsAction.php
  app/Review/Actions/LikeReviewAction.php
  app/Review/Domain/CreateReviewDomain.php
  app/Review/Domain/GetReviewsDomain.php
  app/Review/Domain/LikeReviewDomain.php
  app/Review/Responders/CreateReviewResponder.php
  app/Review/Responders/GetReviewsResponder.php
  app/Review/Responders/LikeReviewResponder.php
  database/migrations/2023_06_29_132501_create_update_review_like_count_trigger.php
  routes/api.php
Labels: ✨ Feature, 📬 API

#31 [#4] ✨ feat : Implement logic for retrieving restaurant information based on ID
  app/Providers/AppServiceProvider.php
  app/Restaurant/Actions/FindRestaurantByIdAction.php
  app/Restaurant/Domain/Repositories/HotpepperRestaurantRepository.php
  app/Restaurant/Domain/Repositories/RestaurantRepositoryInterface.php
  app/Restaurant/Responders/FindRestaurantByIdResponder.php
  app/Services/RecruitApiService.php
  routes/api.php
Labels: ✨ Feature, 📬 API

#32 ✨ feat : Implement user token validation
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  app/Auth/Actions/LoginAction.php
  app/Auth/Actions/SignoutAction.php
  app/Http/Kernel.php
  app/Http/Middleware/VerifyIDToken.php
  app/Profile/Actions/UserShowAction.php
  app/Profile/Actions/UserUpdateAction.php
  routes/api.php
Labels: ✨ Feature, 📬 API
