Repository Tabeyouka/project_TABEYOUKA_laravel-deployment-repo, pull requests merged in 2023-07, with the labels that each got.

#33 refactor(Restaurant ADR): Modify existing Review and Restaurant ADR code
  .gitignore
  app/Like/Actions/LikeReviewAction.php
  app/Like/Domain/Like.php
  app/Like/Responders/LikeReviewResponder.php
  app/Models/Like.php
  app/Models/Restaurant.php
  app/Models/Review.php
  app/Models/User.php
  app/Restaurant/Actions/CreateRestaurantAction.php
  app/Restaurant/Domain/CreateRestaurantDomain.php
  app/Restaurant/Domain/Restaurant.php
  app/Review/Actions/CreateReviewAction.php
  app/Review/Actions/GetReviewsAction.php
  app/Review/Domain/CreateReviewDomain.php
  app/Review/Domain/GetReviewsDomain.php
  app/Review/Domain/LikeReviewDomain.php
  app/Review/Domain/Review.php
  database/migrations/2023_07_01_064420_create_update_restaurant_score_trigger.php
  routes/api.php
Labels: 🔨 Refactor

#34 🎨 refactor : Refactor code to include proper error handling
  app/Recommendation/Actions/RecommendRestaurantsAction.php
  app/Recommendation/Domain/UserGenrePreference.php
  app/Search/Actions/FindNearbyRestaurantsAction.php
  app/Search/Actions/SearchRestaurantsAction.php
  app/Services/RecruitApiService.php
  routes/api.php
Labels: 🔨 Refactor

#35 🎨 refactor : Apply ADR pattern by refactoring codebase
  app/Providers/AppServiceProvider.php
  app/Recommendation/Actions/RecommendRestaurantsAction.php
  app/Recommendation/Domain/Entities/UserGenrePreference.php
  app/Recommendation/Domain/Repositories/UserGenrePreferenceRepository.php
  app/Recommendation/Domain/UserGenrePreference.php
  app/Search/Actions/FindNearbyRestaurantsAction.php
  app/Search/Actions/SearchRestaurantsAction.php
  app/Search/Domain/Entities/RestaurantEntity.php
  app/Search/Domain/Repositories/RestaurantRepository.php
  app/Search/Domain/Restaurant.php
  app/Services/RecruitApiService.php
Labels: 🔨 Refactor

#36 ✨ feat : Implement logic to fetch reviews from followed users
  app/Review/Actions/GetFollowedUsersReviewsAction.php
  app/Review/Domain/Entities/Follow.php
  app/Review/Domain/Repositories/FollowRepository.php
  app/Review/Domain/Review.php
  app/Review/Responders/GetFollowedUsersReviewsResponder.php
  routes/api.php
Labels: ✨ Feature, 📬 API

#37 🎨 refactor: Apply ADR pattern and remove global middleware
  app/Auth/Actions/LoginAction.php
  app/Auth/Actions/SignoutAction.php
  app/Auth/Domains/Repositories/DestroyUser.php
  app/Auth/Domains/Repositories/StoreUserData.php
  app/Auth/Domains/Users.php
  app/Http/Kernel.php
  app/Http/Middleware/VerifyIDToken.php
  app/Profile/Actions/UserShowAction.php
  app/Profile/Actions/UserUpdateAction.php
  app/Profile/Domains/Entities/Users.php
  app/Profile/Domains/Repositories/ShowUserData.php
  app/Profile/Domains/Repositories/UpdateUserData.php
  app/Profile/Domains/Users.php
Labels: 🔨 Refactor, 📬 API

#39 refactor(Actions): Change the declaration method of instance variables in Actions
  app/Like/Actions/LikeReviewAction.php
  app/Like/Actions/UnlikeReviewAction.php
  app/Like/Domain/Entities/Like.php
  app/Like/Domain/Like.php
  app/Like/Domain/Repositories/LikeRepository.php
  app/Restaurant/Actions/CreateRestaurantAction.php
  app/Restaurant/Domain/Entities/Restaurant.php
  app/Restaurant/Domain/Repositories/RestaurantRepository.php
  app/Restaurant/Domain/Restaurant.php
  app/Review/Actions/CreateReviewAction.php
  app/Review/Actions/GetFollowedUsersReviewsAction.php
  app/Review/Actions/GetReviewByIdAction.php
  app/Review/Actions/GetReviewsAction.php
  app/Review/Domain/Entities/Review.php
  app/Review/Domain/Repositories/FollowRepository.php
  app/Review/Domain/Repositories/ReviewRepository.php
  app/Review/Domain/Review.php
Labels: 🔨 Refactor

#40 refactor: Renamed UnlikeReviewAction.php to UnLikeReviewAction.php
  app/Like/Actions/UnLikeReviewAction.php
  routes/api.php
Labels: 🔨 Refactor

#41 🐛 fix : Fix error in loading profile info
  app/Profile/Actions/UserShowAction.php
  app/Profile/Actions/UserUpdateAction.php
Labels: 🐞 BugFix, 📬 API

#42 ✨ feat : Create migration file for user table
  app/Profile/Domains/Entities/Users.php
  database/migrations/2023_07_06_070342_add_bio_to_users_table.php
Labels: 🐞 BugFix, ✨ Feature

#44 feat(review): add find review by user_id
  app/Review/Actions/GetReviewByAction.php
  app/Review/Actions/GetReviewByIdAction.php
  app/Review/Responders/GetReviewByResponder.php
  routes/api.php
Labels: ✨ Feature, 📬 API

#43 ✨ feat : Add functionality to retrieve users followers and followings & create migration file
  app/Profile/Actions/FollowerAction.php
  app/Profile/Actions/FollowingAction.php
  app/Profile/Actions/UserUpdateAction.php
  app/Profile/Domains/Entities/Follows.php
  app/Profile/Domains/Entities/Users.php
  app/Profile/Domains/Repositories/FollowerRepository.php
  app/Profile/Domains/Repositories/FollowingRepository.php
  app/Profile/Domains/Repositories/ShowUserData.php
  app/Profile/Domains/Repositories/UpdateUserData.php
  app/Profile/Responders/FollowerResponder.php
  app/Profile/Responders/FollowingResponder.php
  database/migrations/2023_07_07_172631_create_stories_table.php
  routes/api.php
Labels: ✨ Feature, 📬 API

#46 [#7] ✨ feat : Implement logic to include user location as a search criteria
  app/Search/Actions/SearchRestaurantsAction.php
  app/Services/RecruitApiService.php
  routes/api.php
Labels: ✨ Feature, 📬 API

#47 🎨 refactor : Refactored logic to determine whether the area code belongs to a large or middle area
  app/Search/Actions/SearchRestaurantsAction.php
  app/Services/RecruitApiService.php
  routes/api.php
Labels: 🔨 Refactor, 📬 API

#48 ✨ feat : implement profile page logic, migration file
  app/Profile/Actions/CreateStoryListAction.php
  app/Profile/Actions/EditStoryListAction.php
  app/Profile/Actions/GetStoryAction.php
  app/Profile/Actions/GetStoryListAction.php
  app/Profile/Actions/GetStoryListByIdAction.php
  app/Profile/Actions/UserUpdateAction.php
  app/Profile/Domains/Entities/Stories.php
  app/Profile/Domains/Entities/StoryLists.php
  app/Profile/Domains/Repositories/CreateStoryListRepository.php
  app/Profile/Domains/Repositories/EditStoryListRepository.php
  app/Profile/Domains/Repositories/GetStoryListByIdRepository.php
  app/Profile/Domains/Repositories/GetStoryListRepository.php
  app/Profile/Domains/Repositories/GetStoryRepository.php
  app/Profile/Domains/Repositories/ShowUserData.php
  app/Profile/Responders/CreateStoryListResponder.php
  app/Profile/Responders/EditStoryListResponder.php
  app/Profile/Responders/GetStoryListByIdResponder.php
  app/Profile/Responders/GetStoryListResponders.php
  app/Profile/Responders/GetStoryResponder.php
  app/Review/Domain/Entities/Review.php
  database/migrations/2023_07_07_172631_create_stories_table.php
  database/migrations/2023_07_10_052426_create_stories_table.php
  database/migrations/2023_07_10_154538_add_review_image_to_reviews_table.php
  database/migrations/2023_07_14_123014_add_follower_following_column_on_users_table.php
  database/migrations/2023_07_14_124013_create_update_user_follows_count_trigger.php
  routes/api.php
Labels: ✨ Feature

#50 feat(ReviewRepository): add user data and restaurant data to review object; modify the return type of review
  app/Like/Domain/Entities/Like.php
  app/Profile/Domains/Entities/Follows.php
  app/Restaurant/Domain/Entities/Restaurant.php
  app/Review/Domain/Entities/Review.php
  app/Review/Domain/Entities/ReviewImages.php
  app/Review/Domain/Repositories/ReviewRepository.php
  config/app.php
Labels: ✨ Feature, 🔨 Refactor

#51 🎨 refactor : Improve searching restaurant method
  app/Search/Actions/SearchRestaurantsAction.php
  app/Services/RecruitApiService.php
  composer.json
  composer.lock
  routes/api.php
Labels: 🔨 Refactor, 📬 API

#52 refactor: modify the refactoring part of PR #50 in Eloquent ORM due to inability to set primary_key as composite key
  app/Like/Domain/Entities/Like.php
  app/Profile/Domains/Entities/Follows.php
  app/Restaurant/Domain/Entities/Restaurant.php
Labels: 🐞 BugFix, 🔨 Refactor

#53 Merge branch 'feature/crud-review' into develop
  app/Like/Actions/CheckLikeReviewAction.php
  app/Like/Actions/ToggleLikeReviewAction.php
  app/Like/Domain/Repositories/LikeRepository.php
  app/Like/Responders/CheckLikeReviewResponder.php
  app/Like/Responders/LikeReviewResponder.php
  app/Like/Responders/ToggleLikeReviewResponder.php
  app/Like/Responders/UnLikeReviewResponder.php
  routes/api.php
Labels: ✨ Feature, 🔨 Refactor

#56 🐛 fix : Fix image saving logic
  .github/workflows/main.yml
  Dockerfile
  app/Auth/Domains/Repositories/DestroyUser.php
  app/Auth/Domains/Repositories/StoreUserDataRepository.php
  app/Http/Middleware/VerifyAccessToken.php
  app/Profile/Actions/UserUpdateAction.php
  app/Profile/Domains/Repositories/GetStoryListRepository.php
  app/Profile/Domains/Repositories/GetStoryRepository.php
  app/Profile/Domains/Repositories/UpdateUserData.php
  appspec.yml
  composer.json
  composer.lock
  routes/api.php
Labels: 🐞 BugFix, 📬 API

#57 feat(ReviewRepository): add uploadImage method to upload image to s3 storage
  Dockerfile
  app/Http/Kernel.php
  app/Restaurant/Actions/CreateRestaurantAction.php
  app/Review/Actions/CreateReviewAction.php
  app/Review/Actions/GetReviewByAction.php
  app/Review/Domain/Repositories/ReviewRepository.php
  app/Search/Actions/FindNearbyRestaurantsAction.php
  composer.lock
Labels: ✨ Feature, 🔨 Refactor, 📬 API
