Repository Tabeyouka/project_TABEYOUKA_laravel-deployment-repo, pull requests merged in 2024-01, with the labels that each got.

#67 ♻️ refactor: Improve structure of searchRestaurantsByLocationCode method
  app/Services/RecruitApiService.php
Labels: 🔨 Refactor

#68 🐛 fix : Fix join error
  app/Profile/Domains/Repositories/GetStoryListRepository.php
Labels: 🐞 BugFix, 📬 API

#69 🐛 fix : Fix review list edit error
  app/Profile/Domains/Repositories/EditStoryListRepository.php
  app/Profile/Domains/Repositories/GetStoryListByIdRepository.php
  app/Review/Domain/Entities/Review.php
  app/Review/Domain/Entities/ReviewImages.php
Labels: 🐞 BugFix, 📬 API

#70 Enhancement: Added Detailed Method Documentation in Restaurant Search Methods
  app/Services/RecruitApiService.php
Labels: 📃 Docs
